package searchengine.main;

import java.awt.BorderLayout;    
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.swing.JPanel;
import javax.swing.JTextArea;




public class UserInterface extends javax.swing.JFrame {

    /**
	 * 
	 * 
	 */
	
	private static final long serialVersionUID = 1L;
	/** Creates new form UserInterface 
	 * @throws IOException */
    public UserInterface() throws IOException
    {
        initComponents();
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jComboBox1.setVisible(true);
        client=new Socket("localhost", 4002);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	
    	panel1 = new JPanel();
        cen_panel = new JPanel();
        c_panel = new JPanel();
        text_panel = new JPanel();
        text_area = new JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField("",20);
        jTextField3 = new javax.swing.JTextField("",20);
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Hindu Search Engine");
        setAlwaysOnTop(true);

        //cen_panel.add(jComboBox2);
        cen_panel.add(jTextField2);
        cen_panel.add(jComboBox1);
        cen_panel.add(jTextField3);
        
        c_panel.add(jComboBox2);
        c_panel.add(jButton1);
        
        text_panel.setLayout(new BorderLayout());
        text_area.setText("                        Your results will be displayed here");
        panel1.setBackground(new Color(153, 55, 200));
        text_panel.add(text_area, BorderLayout.PAGE_START);
        text_panel.setBackground(new Color(201,125,120));
       
        Font font = new Font("Algerian", Font.BOLD, 20);
        jLabel1.setFont(font);
        jLabel1.setText("                       Mini-Google Search Engine");
        panel1.setLayout(new BorderLayout());
        panel1.add(jLabel1, BorderLayout.PAGE_START);
        panel1.add(cen_panel, BorderLayout.CENTER);
        panel1.add(c_panel, BorderLayout.PAGE_END);
        panel1.setBackground(new Color(153, 55, 15));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AND", "OR", "NOT" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hash", "list", "myhash", "avl", "bst" }));
        jButton1.setText("Search");
       
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton1ActionPerformed(evt);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        container = getContentPane();
        container.setLayout(new BorderLayout());
        container.add(panel1,BorderLayout.PAGE_START);
        container.add(jTextArea1);
        container.add(text_area);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        //container.add(jScrollPane1);

        pack();
    } //</editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws UnknownHostException, IOException 
    {
    	String temp="";
    	PrintWriter obj=new PrintWriter(client.getOutputStream(),true);
    	BufferedReader ois=new BufferedReader(new InputStreamReader(client.getInputStream()));
    	obj.println(jTextField2.getText()+"\t"+jTextField3.getText()+"\t"+
    	jComboBox1.getSelectedItem()+"\t"+jComboBox2.getSelectedItem());
    	while(true)
    	{
    		String str=ois.readLine();
    		if(str.equals("end"))
    			break;
    		else
    			temp+=str+"\n";
    	}
    	text_area.setText(temp);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new UserInterface().setVisible(true);
				} catch (IOException e) {
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private JTextArea text_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private Socket client;
    private JPanel panel1, cen_panel, c_panel, text_panel;
    @SuppressWarnings("unused")
	private java.awt.Container container;
    // End of variables declaration

}
